# GitHub Actions CI workflow for case2 TDD workshop
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: case2/package-lock.json
    
    - name: Install dependencies
      run: |
        cd case2
        npm ci
    
    - name: Run tests
      run: |
        cd case2
        npm test
